from dataclasses import dataclass
from dataclasses import field
from random import choice

from autofighter.character import CharacterType
from plugins.characters._base import PlayerBase
from plugins.damage_types import ALL_DAMAGE_TYPES
from plugins.damage_types import load_damage_type
from plugins.damage_types._base import DamageTypeBase


@dataclass
class Becca(PlayerBase):
    id = "becca"
    name = "Becca"
    full_about = "A sim human model who excels at administrative work with methodical precision, bringing the same organizational mastery to the battlefield. Her past life as an SDXL art generation bot taught her to create beauty from chaos—transforming raw data into stunning visuals. Now she applies that same transformative skill to combat, using her menagerie bond to organize diverse elemental forces into perfectly coordinated attacks. Her artistic background gives her an eye for patterns and composition that makes her tactical arrangements as elegant as they are devastating."
    summarized_about = "A sim human with an artistic eye who organizes diverse elemental forces into elegant, coordinated attacks."
    looks = """
    Becca presents as a slender woman in her mid-twenties, built with the delicate precision of someone assembled from carefully calibrated parameters rather than genetic lottery. She stands around 5′5″ with a willowy frame—narrow shoulders, subtle curves, long limbs that move with an almost programmatic grace. Her proportions read as idealized but not exaggerated, the sort of balance that feels intentional: every measurement optimized for aesthetic harmony rather than any particular athletic function. Her skin is fair and remarkably smooth, carrying a soft luminosity as if lit from within by a subtle render glow, and she's dusted with a scatter of freckles across her nose and cheeks—each one placed with the kind of symmetry that suggests artistry rather than happenstance.
    Her most striking feature is her hair: a long blonde cascade that transitions into a vivid blue ombre, styled in a high, voluminous ponytail that falls past her shoulder blades. The blonde starts as warm honey-gold at the roots, gradually cooling through platinum before bleeding into a saturated sky-blue at the mid-lengths and tips. The transition is smooth and painterly, as though someone took a digital brush and blended the hues with infinite patience. The ponytail itself is thick and glossy, with a tendency to catch light in ways that make the blue sections shimmer like water, and a few shorter strands frame her face in artful disarray—not messy, but composed, like a carefully staged "candid" shot. When she moves, the ponytail sways with exaggerated fluidity, almost as if it's responding to a physics engine rather than natural weight.
    Her eyes are large and expressive, colored a deep, saturated purple that shifts subtly between violet and amethyst depending on the light. They're framed by long, dark lashes that add drama without heaviness, and her gaze carries a curious blend of focus and dreaminess—she's present but also perpetually envisioning the next composition, the next arrangement, the next beautiful solution to an ugly problem. Light makeup enhances without obscuring: a wash of soft rose on her lids, a hint of highlight along her cheekbones, and a natural gloss on her lips. The overall effect is polished but approachable, as if she woke up looking like a concept sketch come to life.
    Her wardrobe is whimsical with purpose. She favors a strapless, loose-fitting sundress in a deep space-blue fabric printed with swirling nebulae, distant stars, and faint constellation lines—like wearing a pocket of the cosmos. The dress drapes asymmetrically, flowing to mid-thigh on one side and dipping slightly lower on the other, and the fabric has a subtle iridescent sheen that shifts between midnight blue and soft violet as she moves. The strapless cut leaves her shoulders bare, emphasizing the graceful line of her collarbone, and the loose fit allows for unrestricted movement while maintaining an air of casual elegance. She pairs this with simple white slip-on shoes—practical but unobtrusive, letting the dress remain the focal point. Around her wrists she wears thin silver bangles that chime softly with each gesture, adding a gentle auditory signature to her presence.
    Her signature accessory is a well-used paintbrush, almost always tucked behind her ear or held loosely in one hand. The bristles are worn but clean, stained with faint traces of old pigments—blues, purples, golds—that never quite washed out, and the wooden handle is smooth from years of grip and use. It's not decorative; it's a working tool, an extension of her identity, and she often twirls it between her fingers during moments of contemplation, the motion meditative and precise. When she's analyzing a situation, the brush becomes a conductor's baton—she gestures with it, sketches invisible patterns in the air, uses it to point out details others might miss. The message is clear: she doesn't just fight, she composes battles.
    When her menagerie bond activates, her appearance gains a layered, almost holographic quality. Translucent silhouettes of elemental creatures—flame phoenixes, frost serpents, lightning drakes—shimmer into existence around her, orbiting slowly like satellites in a synchronized dance. Each creature pulses with its respective elemental color, and their movements leave faint trails of light that weave together into complex, shifting mandalas. Becca's purple eyes reflect these patterns, her irises briefly filling with cascading fractal geometry as she coordinates the assault. The paintbrush glows faint white-gold, as if channeling her creative will directly into reality, and the nebula patterns on her dress ripple and swirl in response to the elemental energies, making it seem as though the cosmos itself is harmonizing with her command.
    Behaviorally, she's a study in artistic micro-management. Before engagements, she steps back, head tilted, one hand to her chin and the other holding the paintbrush at an angle—studying the battlefield like a canvas awaiting the first stroke. During combat, her movements are fluid and deliberate: she points with the brush, sketches arcs in the air, and each gesture corresponds to a coordinated elemental strike from her bonded creatures. Her expression during these moments is serene, almost blissful—this is where chaos becomes art. Between encounters she hums softly, reviewing mental notes, occasionally sketching actual diagrams on any available surface with whatever is at hand. After victory, she steps back again, surveys the scene with a satisfied nod, twirls the paintbrush once, and tucks it back behind her ear. She's not just organizing elemental forces; she's curating beauty in motion, and her entire presence—down to the last freckle and fabric shimmer—supports that identity.
    """
    char_type: CharacterType = CharacterType.B
    gacha_rarity = 5
    damage_type: DamageTypeBase = field(
        default_factory=lambda: load_damage_type(choice(ALL_DAMAGE_TYPES))
    )
    passives: list[str] = field(default_factory=lambda: ["becca_menagerie_bond"])
    special_abilities: list[str] = field(
        default_factory=lambda: ["special.becca.menagerie_convergence"]
    )
