[project]
name = "Stained-Glass-Odyssey-Idle"
version = "0.1.0"
description = "A game based on our Stained Glass games using chars from the shared world"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "PySide6>=6.10.1",
]

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["endless_idler"]

[dependency-groups]
ci = [
    "pytest>=8.3.5",
    "ruff>=0.11.0",
    "basedpyright>=1.28.1",
]
