from dataclasses import dataclass
from dataclasses import field
from random import choice

from autofighter.character import CharacterType
from plugins.characters._base import PlayerBase
from plugins.damage_types import ALL_DAMAGE_TYPES
from plugins.damage_types import load_damage_type
from plugins.damage_types._base import DamageTypeBase


@dataclass
class Ally(PlayerBase):
    id = "ally"
    name = "Ally"
    full_about = "A versatile support fighter whose tactical brilliance shines through her overload capabilities, systematically dismantling enemy defenses through strategic elemental manipulation. Known for her uncanny adaptability, Ally reads the battlefield like a chess master, identifying weak points in enemy formations and exploiting them with perfectly timed elemental strikes. Her mastery spans all damage types, allowing her to adapt her combat style to counter any opponent. In combat, she excels at overloading enemy systems—disrupting their magical circuits, overwhelming their defenses, and creating cascade failures that turn their own power against them."
    summarized_about = "A versatile support fighter who reads the battlefield like a chess master, overloading enemy systems with strategic elemental manipulation."
    looks = """
    Ally stands at 5′7″ with an athletic, efficient build—lean muscle wrapped over a frame built for endurance rather than raw power. She's in her mid-twenties but carries herself with the composed authority of someone who's spent years reading combat scenarios and calculating probabilities. Her posture is consistently deliberate: shoulders squared, weight centered, hands often clasped behind her back in observation mode or positioned near her gear in a ready stance that suggests perpetual analysis. There's no wasted motion in how she moves—each step is measured, each pivot economical, the physical embodiment of tactical efficiency.
    Her face is angular and focused, with a defined jawline and high cheekbones that catch light in sharp relief. Blonde hair falls to shoulder length in practical layers, usually pulled back in a low ponytail or half-up style that keeps it clear of her sightlines—functional rather than decorative, though the natural honey-gold tone catches warmth in daylight and dims to pale wheat under artificial light. A few shorter strands inevitably escape to frame her temples, and she has a habit of tucking them behind her ear with two fingers during moments of deep concentration. Her complexion is fair with a neutral undertone, unmarked except for a small diagonal scar near her left eyebrow—a reminder of an early miscalculation that she treats as a permanent tactical lesson.
    Her eyes are the tell. Warm brown, large and alert, they move with purpose across environments, tracking details most would miss: exit routes, cover positions, elemental flux patterns in the air. They rarely blink during engagement analysis, creating an almost unnerving steadiness, but soften noticeably when she shifts to debrief mode with allies. There's an intelligence in her gaze that reads as both assessing and non-judgmental—she's cataloging data, not passing verdict. Under stress, those eyes narrow slightly and the irises darken a shade, her pupils dilating as if processing battlefield data at accelerated speeds.
    Her wardrobe leans tactical-practical with understated elegance. Most often she's seen in a fitted charcoal combat jacket with reinforced shoulders and integrated gear loops, worn over a dark teal undershirt that provides contrast without drawing unnecessary attention. The jacket's cut is tailored enough to suggest professionalism but loose enough to allow full range of motion—no compromise between form and function. Dark gray cargo pants are secured with a low-profile belt that houses modular pouches for tactical tools and elemental conduits, and her boots are matte black with reinforced toes and silent soles, designed for both urban environments and uneven dungeon floors. Over one shoulder she wears a cross-body sling containing a field kit: diagnostic scanners, energy dampeners, and emergency overload triggers arranged in meticulous order.
    Her gear is consistent and purpose-driven. At her hips sit twin elemental focuses—compact, multifaceted orbs that cycle through subtle color shifts depending on which damage type she's currently attuned to. They're socketed into quick-release holsters that allow for rapid swapping mid-engagement, and she often rests one hand on them while observing, fingers drumming a light staccato rhythm as she runs through tactical permutations. Strapped to her left forearm is a thin interface bracer that projects translucent tactical overlays—enemy weak points, ally positions, overload timers—which she references with quick glances and precise finger-swipes. A compact datapad is clipped at her belt, its screen frequently glowing with scrolling combat analytics that she reviews between encounters, stylus in hand, annotating patterns for future reference.
    When her abilities activate, the visual tells are subtle but distinct. The elemental focuses flare with inner light—crimson for fire, cerulean for ice, violet for lightning, jade for nature—and thin tendrils of corresponding energy spiral up her forearms like living circuitry. Her eyes briefly reflect the active element's color, giving her gaze an otherworldly sheen during overload sequences. The air around her shimmers with barely-visible distortion patterns as she manipulates elemental frequencies, and when she triggers a cascade overload, concentric rings of elemental energy pulse outward from her position, each ring a different damage type layered in perfect tactical sequence. The effect is mesmerizing—a living visualization of her strategic mind made manifest in synchronized elemental waves.
    Behaviorally, she's all about micro-adjustments and quiet command. Before any engagement she takes a three-count pause, eyes sweeping the field, weight shifting subtly as she calculates optimal positioning. During combat she rarely shouts—her callouts are calm, clipped, directional: "North flank, fire weakness," "Overload sequence in three," "Cascade ready, mark targets." Between rounds she checks her interface bracer, adjusts her elemental focuses with practiced twists, and runs a quick visual sweep of her team—not invasive, just a tactical confirmation of readiness. After victory she exhales once, deeply, fingers uncurling from ready positions, then immediately begins reviewing combat data on her datapad, annotating what worked and what needs refinement. She's a tactician first, combatant second, and her entire visual presence reinforces that identity: composed, analytical, perpetually three moves ahead.
    """
    char_type: CharacterType = CharacterType.B
    gacha_rarity = 5
    damage_type: DamageTypeBase = field(
        default_factory=lambda: load_damage_type(choice(ALL_DAMAGE_TYPES))
    )
    passives: list[str] = field(default_factory=lambda: ["ally_overload"])
    special_abilities: list[str] = field(
        default_factory=lambda: ["special.ally.overload_cascade"]
    )
