from dataclasses import dataclass
from dataclasses import field
from random import choice

from autofighter.character import CharacterType
from plugins.characters._base import PlayerBase
from plugins.damage_types import ALL_DAMAGE_TYPES
from plugins.damage_types import load_damage_type
from plugins.damage_types._base import DamageTypeBase


@dataclass
class Bubbles(PlayerBase):
    id = "bubbles"
    name = "Bubbles"
    full_about = "An enthusiastic aquatic fighter whose bubbly personality masks a devastating combat style built around explosive chain reactions. His bubble burst abilities create cascading detonations that spread across the battlefield like underwater fireworks—each burst triggering additional explosions in a symphony of aquatic destruction. With boundless energy and an infectious optimism, Bubbles approaches every battle like a game, but his seemingly playful attacks pack tremendous force. His mastery of pressure dynamics allows him to create bubble formations that can both shield allies and devastate enemies when they inevitably pop."
    summarized_about = "An enthusiastic aquatic fighter who creates cascading bubble explosions, turning playful attacks into devastating chain reactions."
    looks = """
    Bubbles is, quite literally, a bubble—a spherical mass of aquatic energy approximately four feet in diameter when at rest, though this dimension fluctuates wildly based on mood, combat intensity, and environmental pressure. The sphere's membrane is translucent but not fully transparent, carrying a soft opalescent quality that refracts light into gentle rainbow gradients across its surface. In calm moments, the membrane holds a stable, soap-bubble sheen—pale blues bleeding into pinks, golds, and silvers—but under stress or excitement, those colors intensify and pulse, chasing each other across the surface in rapid, joyful sequences. The overall effect is mesmerizing: a living prism that seems perpetually on the verge of bursting but never quite does.
    The interior of the sphere is where Bubbles' "personality" becomes visible. Suspended within the aquatic membrane are hundreds of smaller micro-bubbles, ranging from pinpoint specks to marble-sized orbs, all drifting in constant, lazy motion. These micro-bubbles are the key to reading Bubbles' emotional state: when he's content, they drift slowly in gentle spirals; when excited, they bounce and collide in chaotic pinball patterns; when focused in combat, they align into geometric formations—grids, helixes, concentric rings—that pulse in rhythm with his attack sequences. Each micro-bubble carries its own faint luminescence, glowing soft cyan, aquamarine, or pearl-white, and together they create an internal constellation that shifts and reorganizes like a living mood ring.
    Movement is a study in fluid dynamics made whimsical. Bubbles doesn't walk—he floats, bobs, and bounces, propelling himself through the air with a combination of internal pressure shifts and what can only be described as aquatic enthusiasm. When moving casually, he drifts along at about chest height to most humanoids, swaying gently as if caught in an invisible current. When excited, he bounces energetically, sometimes gaining several feet of altitude before settling back down, and the membrane deforms slightly with each impact—flattening at the base, rippling outward—before snapping back into perfect spherical tension. In combat, his motion becomes more deliberate: he spins rapidly to generate momentum, contracts into a tighter sphere to build pressure, or elongates slightly into an ovoid shape to streamline his trajectory. Every motion is accompanied by a soft, liquid sloshing sound—gentle and oddly soothing despite the potential violence of his abilities.
    Surface details provide additional texture to his appearance. The membrane isn't perfectly uniform; it carries subtle variations in thickness that create soft, swirling patterns—like oil on water, but three-dimensional and alive. Occasionally, tiny droplets of condensed water form on the exterior and roll down the sphere's surface, leaving brief trails of extra refraction before evaporating into mist. When Bubbles expresses strong emotion, the membrane develops temporary "dimples"—small indentations that press inward as if an invisible hand is poking the surface—and these dimples often cluster to form simple facial expressions: two dimples for eyes, one for a mouth, creating a cheerful, ever-shifting countenance. It's not a permanent face, but a momentary suggestion of one, gone as soon as the emotion passes.
    When his bubble burst abilities activate, the visual spectacle intensifies dramatically. The micro-bubbles within his sphere begin to glow brighter, their cyan light pulsing in rapid staccato bursts, and new bubbles spawn at an accelerated rate, crowding the interior until the whole mass seems ready to rupture from internal pressure. Then, with a sound like champagne bottles uncorking in sequence, Bubbles ejects dozens of smaller satellite bubbles from his membrane—each one a foot in diameter, glowing with stored kinetic energy, and trailing faint streams of mist. These satellite bubbles drift toward enemies with deceptive laziness before detonating in brilliant aquatic flashes—cyan light, concussive force, and showers of prismatic droplets that trigger chain reactions in adjacent bubbles. During these moments, Bubbles himself shrinks slightly, as if redistributing his mass into the attacks, only to swell back to full size once the sequence completes, the membrane glowing with satisfied luminescence.
    Behaviorally, every motion is infused with enthusiasm. Before a fight, Bubbles bounces in place with mounting excitement, the micro-bubbles inside swirling faster and faster, and the membrane's colors cycle through rapid chromatic shifts—blue to violet to gold and back again. During combat, he spins and wobbles with what reads as glee, the dimple-face appearing frequently in expressions of determined joy. After victory, he performs a series of exuberant vertical bounces, each one higher than the last, trailing arcs of mist and tiny celebratory bubbles that pop harmlessly in the air like confetti. If an ally is nearby, he'll drift close and "bump" against them gently—a full-body high-five of sorts—leaving a faint damp spot and a lingering sense of aquatic camaraderie. Despite the lack of a fixed face or humanoid body language, Bubbles' emotions are never ambiguous: he is joy made tangible, optimism given form, a living reminder that even in combat, there's room for play. And when he explodes into cascading devastation, he does so with the infectious delight of someone who knows that every ending is just the setup for another beautiful burst.
    """
    char_type: CharacterType = CharacterType.A
    gacha_rarity = 5
    damage_type: DamageTypeBase = field(
        default_factory=lambda: load_damage_type(choice(ALL_DAMAGE_TYPES))
    )
    passives: list[str] = field(default_factory=lambda: ["bubbles_bubble_burst"])
