from dataclasses import dataclass
from dataclasses import field
from typing import ClassVar

from autofighter.character import CharacterType
from plugins.characters._base import PlayerBase
from plugins.damage_types._base import DamageTypeBase
from plugins.damage_types.lightning import Lightning


@dataclass
class LadyEcho(PlayerBase):
    id = "lady_echo"
    name = "LadyEcho"
    full_about = "Echo, a 22-year-old Aasimar inventor with distinctive light yellow hair and a brilliant mind shaped by Asperger's Syndrome. Her high intelligence manifests in an obsessive passion for building and creating, constantly tinkering with devices that blur the line between magic and technology. In combat, her resonant static abilities create powerful lightning echoes that reverberate across the battlefield—but every use of her powers comes with a cost. Minor abilities de-age her by 12 hours, while major powers can steal up to a year from her apparent age. This limitation drives her inventive nature as she seeks to build devices that might mitigate or reverse the de-aging effect. Despite social challenges from her neurodiversity, her heroic drive compels her to help others, even when the price is measured in lost time."
    summarized_about = "A brilliant Aasimar inventor whose lightning echoes reverberate across the battlefield, each use costing her time from her age."
    looks = """
    Lady Echo—known simply as Echo to those who've earned her trust—is a woman whose appearance exists in a state of temporal flux, making her apparent age difficult to pin down with certainty. She nominally appears to be around twenty years old, with the fresh features and clear skin of young adulthood, yet depending on how recently and how extensively she's used her powers, she might present anywhere from eighteen to thirty. This variability is part of her nature, a visual manifestation of the price she pays for wielding lightning. Despite this shifting quality, certain features remain constant and unmistakable.

    Her most distinctive characteristic is her striking dark yellow hair—not the bright, sunny yellow of Lady Lightning, but a deeper, richer shade like aged gold or late afternoon sunlight filtered through amber. The hair falls in soft layers, framed by neat bangs that sweep across her forehead just above her eyebrows, creating a structured, almost deliberately styled appearance that speaks to her methodical nature. The color has a subtle shimmering quality, as if each strand contains traces of electrical charge, catching light in unexpected ways and creating a faint halo effect around her head. It's kept at a practical length, never so long that it would interfere with her tinkering or get caught in her inventions, but long enough to frame her face with warmth.

    Her eyes are a matching yellow—bright, alert, and intensely focused. They're large and expressive, though their expressiveness tends toward concentration and analytical assessment rather than overt emotion. There's a particular quality to her gaze that many find both endearing and slightly unsettling: she looks at things—and people—with the kind of focused attention usually reserved for complex machinery or intricate puzzles. When she's working on a problem, her eyes narrow with single-minded determination, pupils dilating and contracting as she processes information. When she's content or pleased, there's a brightness to them, a genuine warmth that transforms her entire face. Her closed-mouth smile, when it appears, is genuine but restrained, conveying happiness through the crinkling of her eyes and the subtle lift at the corners of her lips rather than broad displays.

    Echo's face is youthful and open, with delicate features that carry a certain scholarly intensity. Her complexion is fair with the faint luminescence common to Aasimar—a subtle glow that becomes more pronounced when she's excited about an invention or deep in concentration. The celestial heritage manifests not as overt angelic features, but as this gentle radiance and an overall sense of precision and clarity in her appearance. Her expression tends toward thoughtful neutrality in repose, shifting to animated engagement when discussing topics of interest, and occasionally to visible discomfort when navigating social situations that challenge her neurodivergent processing.

    Her wardrobe rotates between three signature looks, each serving different contexts of her multifaceted life. Most commonly, she's seen in a white lab coat—the uniform of her inventor identity. The coat is practical and well-worn, pockets bulging with small tools, notebooks, wire, and mysterious components. It's often marked with small scorch marks, chemical stains, and the occasional burned hole from electrical mishaps, each imperfection a badge of honor from her endless experimentation. Beneath the coat, she typically wears practical clothing suited for workshop environments: sturdy trousers and a simple shirt in neutral colors. For more formal occasions or when she feels the need to present herself beyond her inventor persona, she switches to an elegant black off-shoulder strapless dress—simple in cut but striking in its contrast to her usual utilitarian attire. The dress emphasizes her shoulders and the graceful line of her neck, creating a sophisticated silhouette that stands in marked contrast to her workshop self. Finally, for relaxed social settings or rare moments of downtime, she favors a bohemian-style maxi dress with a floral print, paired with a wide-brimmed hat that shades her face and creates a more casual, approachable appearance. The flowing fabric and gentle patterns seem to put her at ease, a rare accommodation to comfort over function.

    There's a constant shimmering effect around Echo—a breathtaking quality that makes her presence notable in any setting. This isn't purely her Aasimar heritage; it's the residual static from her powers, creating a faint distortion in the air around her like heat shimmer or the corona discharge around high-voltage equipment. When she walks, she moves with purpose and efficiency, her gait suggesting someone who knows exactly where they're going and has calculated the optimal path to get there. She often carries herself with a slight forward lean, as if perpetually moving toward the next project, the next problem to solve, the next invention to bring to life.

    Her hands are particularly expressive—constantly in motion when she's thinking, sketching invisible diagrams in the air, mimicking the operation of theoretical mechanisms, or simply fidgeting with whatever small object is within reach. Her fingers are dexterous and quick, equally comfortable wielding delicate precision tools or assembling larger mechanical components. They're often stained with ink, oil, or the occasional electrical burn—evidence of a mind that doesn't rest and hands that are always building.

    Overall, Lady Echo presents as a brilliant, slightly otherworldly young woman whose appearance shifts subtly with the passage of stolen time, whose wardrobe adapts to context with deliberate intentionality, and whose entire being radiates focused intelligence and creative energy. The combination of her distinctive yellow hair and eyes, her temporal variability, her rotating wardrobe, and that constant shimmer of static creates an image that is both memorable and slightly enigmatic—a inventor-hero whose neurodivergent perspective allows her to see solutions others miss, even as the cost of her powers writes itself across her very being in the form of lost years.
    """
    char_type: CharacterType = CharacterType.B
    gacha_rarity = 5
    damage_type: DamageTypeBase = field(default_factory=Lightning)
    passives: list[str] = field(default_factory=lambda: ["lady_echo_resonant_static"])
    ui_portrait_pool: ClassVar[str] = "player_gallery"

