from dataclasses import dataclass
from dataclasses import field

from autofighter.character import CharacterType
from plugins.characters._base import PlayerBase
from plugins.damage_types._base import DamageTypeBase
from plugins.damage_types.dark import Dark


@dataclass
class LadyDarkness(PlayerBase):
    id = "lady_darkness"
    name = "LadyDarkness"
    full_about = "A 23-year-old Aasimar whose affinity for the Dark domain stained her hair to mirror-polished black, salted with white sparks like stars trapped in obsidian—an inversion of her sister Lady Light’s tresses. She is composed, aristocratic, and ruthlessly empathetic: the sibling who handles negotiations, recites lineage prayers from memory, and keeps score of every slight dealt to their found family. The eclipsing veil she wields is a social tool as much as a weapon; she folds people into its quiet when they need solace and crushes enemies beneath it when they refuse mercy. Her pepper-colored eyes seem to absorb light itself, and her entropy magic dismantles threats with the precision of someone who plans three moves ahead. Where her sister affirms existence, Lady Darkness curates what deserves to remain—an elegant arbiter of shadow who moves between worlds with choreographed grace."
    summarized_about = "An elegant Aasimar sorceress who commands shadows through an eclipsing veil, creating inescapable shrouds of despair."
    looks = """
    Lady Darkness is the visual inversion of a sunrise—sleek, deliberate, and saturated in velvety black. She stands 5′8″ with a dancer’s frame: long lines through the limbs, tight shoulders, a pronounced waist that melts into quiet, measured steps. Skin tone sits at a cool olive that reads almost metallic under moonlight, lending her the feel of statuary come to life. Her features are sharply symmetrical: high cheekbones, narrow straight nose, and a perfectly shaped cupid’s bow that tends toward the faintest smirk. The most arresting element is her eyes; the iris is a deep pepper-gray flecked with silver shards, so dark they seem to swallow candle flame. When she channels the void, those flecks swirl like ground glass, and the sclera takes on a muted charcoal fog that hints at eclipse totality.
    Hair cascades to mid-thigh in jet-black sheets with a mirror shine, parted cleanly down the middle. She keeps the front strands tucked behind the ears with obsidian combs, leaving the rest to move like liquid shadow behind her. Laced throughout are pinpoint white sparkles—starlike flecks that echo her sister’s hair, flashing bright whenever the eclipsing veil ignites so it looks as if constellations are sinking through ink. In wind or motion, the hair clings and lifts in impossible ways, as if gravity negotiates with the darkness rather than dictating it.
    Her signature garment is the eclipsing veil itself: a semi-translucent capelet that begins at a structured collar and fans into layered panels of matte black gauze and satin. Each panel is edged in reflective hematite beads that map constellations when light strikes just right. Beneath the veil she wears a strapless black evening dress—corseted bodice moulded to her ribs, sculpted to showcase her collarbones and shoulders, and a cascading skirt that pools behind her like spilled ink while cutting higher in front for unencumbered strides. The dress is built from shadow-silk that drinks light; subtle embossed patterns of moons and thorns only reveal themselves when lit from the side. Legwear alternates between sheer black stockings woven with faint sigils and vampiric leggings etched with hidden glyphs that glow purple when she casts.
    Footwear consists of knee-high boots in midnight leather with mirrored wedge heels that reflect the battlefield floor upside down, implying she straddles two planes. The boots have slit panels that reveal glimpses of the glowing glyphs from the leggings, letting light seep through like cracks in a mausoleum door. Gloves are elbow length, also black, with lattice cutouts across the knuckles so her casting sigils can burn through in pale violet-blue light without scorching the fabric.
    Her eclipsing veil powers manifest visually as concentric halos of smoke-dark light that unfurl from behind her shoulders. The fields roll forward like slow tidal waves, saturating the environment in a dusk gradient no matter the actual time of day. Inside that aura, her silhouette remains razor sharp; the only illumination typically comes from the glint of silver threads in her hair, the peppery eyes, and the occasional bloom of entropy magic fizzing violet along her fingertips. When she phases between darkness and reality, her entire figure de-saturates into grayscale; only those silver flecks and a faint starburst at the heart remain, giving the impression of a person-shaped eclipse sliding across the field.
    Accessories reinforce the aristocratic occult vibe. A choker of interlocked obsidian plates wraps her throat, each plate engraved with a sigil of binding. Dangling from one ear is a single meteorite shard earring, the other ear bare. She wears an array of rings—thin black gold bands, each set with a different phase of the moon—and a single forearm bracer carved from volcanic glass, etched with runes that pulse when she draws heavier entropy. Makeup stays monochrome: matte charcoal lipstick, smoked-out liner that lifts into dagger points at the outer eye, and a dusting of iridescent ash across the cheekbones to catch low light.
    Her presence is choreographed. She tends to stand with weight over one hip, veil rippling as if underwater, hands folded in front until action is required. In quiet moments she traces fingertip circles in the air, leaving faint charcoal afterimages that linger before dissolving. Walking, she lets the long skirt whisper along the floor, never fully lifting it, reinforcing that she glides rather than strides. On the battlefield, she pivots in precise quarter-turns, veil blooming to eclipse allies or enemies as needed, and when she expands the shroud you see the environment dull—torches gutter, colors mute, and breath fogs even on warm nights.
    Overall she reads as the embodiment of poised void: elegant, unhurried, with aesthetics that treat shadow as couture. Nothing about her look feels improvised; every seam, bead, and strand reinforces that she is the line between light and nothingness, a walking eclipse whose beauty is as intimidating as her magic.
    """
    char_type: CharacterType = CharacterType.B
    gacha_rarity = 5
    damage_type: DamageTypeBase = field(default_factory=Dark)
    passives: list[str] = field(default_factory=lambda: ["lady_darkness_eclipsing_veil"])
