from dataclasses import dataclass
from dataclasses import field

from autofighter.character import CharacterType
from plugins.characters._base import PlayerBase
from plugins.damage_types._base import DamageTypeBase
from plugins.damage_types.light import Light


@dataclass
class LadyLight(PlayerBase):
    id = "lady_light"
    name = "LadyLight"
    full_about = "A 23-year-old Aasimar whose soul aligned so purely with the Light domain that her hair bleached to lunar white threaded with black starlike flecks. Sister to Lady Darkness, she plays the role of steady hearth-fire: the soft-spoken guardian who remembers everyone’s schedules, writes encouragement notes, and volunteers for the final watch so others can sleep. Cotard's Syndrome still steals sensation from her left arm and blinds the right eye, but she refuses to let the illness define her. Therapy sessions every six hours keep her body moving, while radiant aegis drills keep her hope sharp. When she steps between an ally and danger, the gesture feels less like a spell and more like a promise—she will hold the line, believe in their existence, and lend them her light even when she doubts her own."
    summarized_about = "An Aasimar battling Cotard's Syndrome who creates protective light barriers to affirm existence against the void she perceives within."
    looks = """
    Lady Light stands 5′6″ with the delicate musculature of someone who splits her days between therapy harnesses and shield drills. Her build is straight-lined and hollowed at the shoulders, yet she carries herself with ballerina poise: chin lifted, sternum square, feet always set as though she expects to absorb the next impact. Skin runs porcelain pale with a cool undertone that catches ambient color; it bloom-fades from soft rose to chalk depending on circulation, leaving faint constellations of freckles across her nose and collarbones. The right half of her face is alert, the eye a clear opalescent gold rimmed in long, pale lashes; the left eye has milked over into lavender-grey and rarely fully opens, creating an asymmetrical, haunted gaze that still manages serenity rather than fright.
    Her hair remains the easiest tell. It spills past her hips in thick white sheets, but every strand is peppered with micro-thin black sparkles, like starfields trapped in snowfall. Those flecks catch light and pulse when her magic stirs, giving the impression that the hair itself remembers the cosmos even when her mind doubts her body. She keeps the mass swept forward over her nonresponsive left arm, letting it act as a shimmering shawl. The untreated portion of the hair at the crown frays into soft flyaways that arc slightly under static, mirroring the faint halo of radiance she maintains even off-duty. When her radiant aegis flares, the black specks flash in sequence from scalp to tip, tracing the flow of power through her body like a visible heartbeat.
    The left arm is restrained in a sculpted sling of white leather and silk webbing, strapped across her torso beneath a pearl satin bodice. The sling’s edges are embroidered with black beadwork to echo the sparkles in her hair, reinforcing that the limb is still hers even in stillness. Fingers peek out in silver splints, nails painted a soft mother-of-pearl gradient to avoid drawing pity. Therapy leaves pale bruises and crescent scars along the clavicle; she covers the worst with translucent kinesiology tape inscribed with tiny solar sigils. Her functioning right arm wears a fitted, filigreed vambrace of mirrored steel over a compression glove traced with light-conductive circuits—more jewelry than armor until it ignites.
    Wardrobe focuses on soft silhouettes and controlled glow. Her primary outfit is a strapless, floor-length white dress—pearlescent bodice molded to her ribs, layered chiffon skirt that spills to the ankle with hand-dipped charcoal hems so every step trails a faint gray afterimage. The dress is built onto a hidden structure that supports the sling, letting the gown read as effortless despite the adaptive hardware beneath. Over her shoulders drapes an asymmetrical organza mantle, fastening on the right side and caping down the left to hide the sling; the fabric carries refractive threads that scatter light into prismatic shards whenever she pivots. A narrow belt in matte black leather houses ampoules, therapy tools, and the triggers for her radiant aegis, while an under-layer of sheer stockings feeds into knee-high boots of lacquered white leather with mirrored insets along the shin—visual confirmation points she can glance at when dissociation hits. The overall silhouette is luminous, formal, and at once fragile and impenetrable.
    Her light magic adds further visual vocabulary. When she casts, translucent hexagonal plates blossom outward from her sternum, rimmed with white fire that bleeds violet at the edges. Those plates bend around her allies like petals, projecting faint refractions of their silhouettes onto the floor so she can “see” their existence even when her senses falter. The conductive leads woven inside her bodice glow faint gold in idle moments, then blaze black-and-white circuitry that leapfrogs across her collarbone when she overclocks the shield. Every activation raises a faint corona over her hair, echoing the black sparkles like reversed starlight.
    Accessories double as anchors to reality: a rosary of hematite and opal loops her throat; she rolls the beads against her pulse when Cotard’s episodes whisper that she’s fading. A silver ear cuff on the right ear houses a discreet auric monitor, and a matching thumb ring on her good hand carries Cassy’s initials as a tactile reminder of the people she protects. She favors minimal cosmetics—just a wash of soft gold across the left eyelid and a swipe of clear gloss—but keeps a compact mirror clipped at her belt to verify her reflection before every mission.
    Behavior completes the read. She counts breaths before stepping into any room, tapping fingers against the mirrored boot plates in a quiet “one-two-I-am-here” rhythm. In conversation she turns her working eye fully toward the speaker while the blind eye softens, creating an almost benediction-like attention. During combat she pivots from the hips, skirt flaring while the sling stays fixed, and her free hand sketches air sigils that bloom into shields before her allies even register danger. Victory doesn’t bring celebration—only a slow exhale, fingertips brushing the blind eye, then a gentle press of knuckles to each teammate’s sternum as if confirming their continued existence. Visually she is a living votive candle: white flame lined with midnight sparks, determined to keep every soul around her illuminated.
    """
    char_type: CharacterType = CharacterType.B
    gacha_rarity = 5
    damage_type: DamageTypeBase = field(default_factory=Light)
    passives: list[str] = field(default_factory=lambda: ["lady_light_radiant_aegis"])
